# How long the hunters should get blindness and slowness when the match starts.
headStartDuration: 30
# Set to true to start the game by having a runner hit a hunter, instead of using the /start command.
startGameByHit: false
# Set to true to allow the compass to work in the nether.
compassEnabledInNether: true
# Set to true to put runners in spectator mode when they die.
setRunnersToSpecOnDeath: true
# Set to true to send anonymized, aggregated usage data to help improve the plugin.
sendUsageData: true

# You can change the colours of the teams here.
# Only one colour is supported.
huntersColor: "&c"
runnersColor: "&a"
spectatorsColor: "&b"

# Read the plugin README/description for more info on how to set up Discord integration!
enableDiscord: false
discordToken: "XXXXX"
ip: "a minecraft server"
processDiscordCommands: true

discordServerId: "XXXXX"
musicChannelId: "XXXXX"
hunterRoleId: "XXXXX"
runnerRoleId: "XXXXX"
spectatorRoleId: "XXXXX"

# Please do not touch the value below!
uuid: ""