# How long the hunters should get blindness and slowness when the match starts.
headStartDuration: 30
# Set to true to allow the compass to work in the nether.
compassEnabledInNether: true
# Set to true to send anonymized, aggregated usage data to help improve the plugin.
sendUsageData: true

# *****************
# * EXTRA OPTIONS *
# *****************

# You can change the colors of the teams here.
huntersColor: "&c"
runnersColor: "&a"
spectatorsColor: "&b"

# Set to true to put runners in spectator mode when they die.
setRunnersToSpecOnDeath: true
# Set to true to clear runner inventories and EXP when the game starts.
clearRunnerInvOnStart: false
# Set to true to clear hunter inventories and EXP when the game starts.
clearHunterInvOnStart: false
# Set to true to clear all item drops when the game starts.
clearItemDropsOnStart: false
# Set to true to set the world time to 0 when the game starts.
setTimeToZero: true
# Set to true to start the game by having a runner hit a hunter, instead of using the /start command.
startGameByHit: false
# Set to true to enforce a world border before the game starts (useful to keep players from running too far).
preGameWorldBorder: false
# This will set the size of the pre-game border. Recommended to leave at 100.
preGameBorderSize: 100

# ***********
# * DISCORD *
# ***********

# Read the plugin README/description for more info on how to set up Discord integration!
enableDiscord: false
discordToken: "XXXXX"
ip: "a minecraft server"
processDiscordCommands: true

discordServerId: "XXXXX"
musicChannelId: "XXXXX"
hunterRoleId: "XXXXX"
runnerRoleId: "XXXXX"
spectatorRoleId: "XXXXX"

# Please do not touch the value below!
uuid: ""